// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfeOO2D5h-1HfiEBwo-taKW8AA1sA2hfM',
    appId: '1:379764789871:web:6e453cda7636c9456df39a',
    messagingSenderId: '379764789871',
    projectId: 'mukulkalambe',
    authDomain: 'mukulkalambe.firebaseapp.com',
    storageBucket: 'mukulkalambe.firebasestorage.app',
    measurementId: 'G-XPQ5DFC37J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv7WSCxcn29FKSB2Gsj42hDzJWzh0Ag8w',
    appId: '1:379764789871:android:0bceb498fc25cc706df39a',
    messagingSenderId: '379764789871',
    projectId: 'mukulkalambe',
    storageBucket: 'mukulkalambe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqgMuwKfNpNYoccjEqlORBOewBdYw6T_g',
    appId: '1:379764789871:ios:0578a6afe018231d6df39a',
    messagingSenderId: '379764789871',
    projectId: 'mukulkalambe',
    storageBucket: 'mukulkalambe.firebasestorage.app',
    iosBundleId: 'com.example.myportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqgMuwKfNpNYoccjEqlORBOewBdYw6T_g',
    appId: '1:379764789871:ios:0578a6afe018231d6df39a',
    messagingSenderId: '379764789871',
    projectId: 'mukulkalambe',
    storageBucket: 'mukulkalambe.firebasestorage.app',
    iosBundleId: 'com.example.myportfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfeOO2D5h-1HfiEBwo-taKW8AA1sA2hfM',
    appId: '1:379764789871:web:6942f3bbee0811a16df39a',
    messagingSenderId: '379764789871',
    projectId: 'mukulkalambe',
    authDomain: 'mukulkalambe.firebaseapp.com',
    storageBucket: 'mukulkalambe.firebasestorage.app',
    measurementId: 'G-B4YFN5C2YK',
  );
}
